#最大连接数
http:
  maxTotal: 1000
#并发数
  defaultMaxPerRoute: 2000
#创建连接的最长时间
  connectTimeout:  80000
#从连接池中获取到连接的最长时间
  connectionRequestTimeout: 10000
#数据传输的最长时间
  socketTimeout:  200000
#提交请求前测试连接是否可用
  staleConnectionCheckEnabled:  true
