spring:
  redis:
    database: 0
    cluster:
      nodes: 192.168.176.128:6379,192.168.176.128:6380,192.168.176.128:6381,192.168.176.128:6382,192.168.176.128:6383,192.168.176.128:6384
      max-redirects: 3  # 获取失败 最大重定向次数
redis:
  timeout: 10000 #客户端超时时间单位是毫秒 默认是2000
  maxIdle: 300 #最大空闲数
  maxTotal: 1000 #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
  maxWaitMillis: 1000 #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
  minEvictableIdleTimeMillis: 300000 #连接的最小空闲时间 默认1800000毫秒(30分钟)
  numTestsPerEvictionRun: 1024 #每次释放连接的最大数目,默认3
  timeBetweenEvictionRunsMillis: 30000 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
  testOnBorrow: true #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
  testWhileIdle: true #在空闲时检查有效性, 默认false
  password: wulei123 #密码

#最大连接数
http:
  maxTotal: 1000
#并发数
  defaultMaxPerRoute: 2000
#创建连接的最长时间
  connectTimeout:  80000
#从连接池中获取到连接的最长时间
  connectionRequestTimeout: 10000
#数据传输的最长时间
  socketTimeout:  200000
#提交请求前测试连接是否可用
  staleConnectionCheckEnabled:  true

person:
  my_name: hehe

es:
  host: 192.168.176.128
  port: 9200
  scheme: http
# 打印sql
logging:
  config: classpath:logback-spring.xml
